# Generated by Django 4.0.6 on 2022-09-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dowellchat', '0002_rename_room_message_room_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_link',
            new_name='room',
        ),
    ]
