# Generated by Django 3.2.3 on 2022-08-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.CharField(default='Member', max_length=1000),
        ),
    ]
