# Generated by Django 3.2.3 on 2022-08-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.CharField(blank=True, default='Member', max_length=1000, null=True),
        ),
    ]
