# Generated by Django 3.2.3 on 2022-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.CharField(blank=True, default='Member', max_length=1000),
        ),
    ]
