# Generated by Django 4.0.6 on 2022-09-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
