# Generated by Django 4.0.6 on 2022-09-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apiCsvUpload',
        ),
        migrations.DeleteModel(
            name='apiMessage',
        ),
        migrations.DeleteModel(
            name='apiRoom',
        ),
    ]
